config:
    delay-between-messages: 250
    delay-between-same-messages: 3000
debug:
    enabled: false
channels:
  global:
    format: '§f<{1}§r§f>: {2}'
  message-sent-msg: Message sent.
  minimum-score-no-send: 50
  partially-offensive: 0.75
zones:
    chat:
        enabled: false
        excluded-filters:
    signs:
        enabled: true
        excluded-filters:
            - duplicate-messages
            - leet
    channel:
        enabled: true
        excluded-filters:
filters:
    duplicate-messages:
        default-level: 10
        priority: 5
    bubbles:
        default-level: 0
        priority: 4
    server-ip:
        default-level: 4
        priority: 1
        expressions:
            - regex: "((http)s?:\\/\\/)?[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*(\\.[a-zA-Z]{2,4})(\\/[a-zA-Z0-9\\?-_\\+=]*)*"
              level: 10.0
            - regex: "([0-9]{1,3}\\.){3}[0-9]{1,3}"
              level: 10.0
        whitelist:
            - "oc.tc"
            - "twitch.tv"
            - "hitbox.tv"
            - "twitter.com"
            - "youtube.com"
            - "zildith.net"
    leet:
        default-level: 2
        priority: 5
    repeated-characters:
        priority: 2
        count: 5
    all-caps:
        default-level: 12
        priority: 3
        max-length: 4
    profanity:
        default-level: 10
        priority: 6
        whitelist:
            - "snowball|snowballs"
            - "decanus"
            - "bass"
        templates:
            tmp1:
                expression: "\\b%FIRST+%REST+|%FIRST+%REST+\\b"
                default: false
            tmp2:
                expression: "%WHOLE"
                default: true
            tmp3:
                expression: "\\b(%WHOLE)\\b"
                default: false
        words:
            "nigger":
                level: 55
            "fuck":
                level: 10
            "motherfuck":
                level: 10
            "cunt":
                level: 15
            "fag":
                level: 15
            "faggot|queer":
                level: 15
            "cock":
                level: 10
            "erection":
                level: 5
            "dick":
                level: 10
            "bastard|basterd":
                level: 5
            "penis":
                level: 5
            "pussy":
                level: 10
            "poon":
                level: 10
            "whore":
                level: 10
            "ejaculate|ejaculat":
                level: 6
            "anus|arse":
                template: tmp3
                level: 3
            "bitch":
                level: 10
            "slut":
                level: 6
            "wank":
                level: 16
            "clit":
                level: 10
            "anal":
                level: 10
                template: tmp3
            "goatse":
                level: 6
            "bukake":
                level: 6
            "dildo":
                level: 6
            "skeet":
                level: 6
            "clit":
                level: 6
            "tits":
                level: 5
            "twat":
                level: 6
            "titties":
                level: 5
            "ass|asshole|assface|badass":
                level: 4
                template: tmp3
            "boner":
                level: 4
            "douche":
                level: 5
            "shit":
                level: 5
            "masturbate|masterbate":
                level: 6
            "porn":
                level: 4
            "blowjob":
                level: 4
            "piss":
                level: 1
